import Header from "@components/components/Header";
import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";

const merriweather = Merriweather({
  weight: [ '300', '400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Jossy_Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} w-[90%] lg:w-[85%] m-auto pt-[20px] lg:pt-[50px] pb-[10px] bg-[#06070A] text-[white]`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
